# Generated by Django 5.2.6 on 2025-11-21 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial_commentaires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='dislike',
            field=models.ManyToManyField(related_name='commentaire_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='like',
            field=models.ManyToManyField(related_name='commentaire_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='texte',
            field=models.TextField(),
        ),
    ]
